//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Control.LFWSrpt {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="laf_webServices_invoicec_infoAutSRIString_infoAutSRIString_Binder", Namespace="http://latwisqa02.am.qua.lafargeone.net/laf.webServices.invoicec.infoAutSRIString" +
        ":infoAutSRIString")]
    public partial class lafwebServicesinvoicecinfoAutSRIStringinfoAutSRIString : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ntfyElectronicVouchersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public lafwebServicesinvoicecinfoAutSRIStringinfoAutSRIString() {
            this.Url = global::Control.Properties.Settings.Default.Control_LFWSrpt_laf_webServices_invoicec_infoAutSRIString_infoAutSRIString;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ntfyElectronicVouchersCompletedEventHandler ntfyElectronicVouchersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("laf_webServices_invoicec_infoAutSRIString_infoAutSRIString_Binder_ntfyElectronicV" +
            "ouchers", RequestNamespace="http://latwisqa02.am.qua.lafargeone.net/laf.webServices.invoicec.infoAutSRIString" +
            ":infoAutSRIString", ResponseNamespace="http://latwisqa02.am.qua.lafargeone.net/laf.webServices.invoicec.infoAutSRIString" +
            ":infoAutSRIString", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("o_status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ntfyElectronicVouchers([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] infoAutSRIString infoAutSRIString, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string debug, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] out string o_message) {
            object[] results = this.Invoke("ntfyElectronicVouchers", new object[] {
                        infoAutSRIString,
                        debug});
            o_message = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ntfyElectronicVouchersAsync(infoAutSRIString infoAutSRIString, string debug) {
            this.ntfyElectronicVouchersAsync(infoAutSRIString, debug, null);
        }
        
        /// <remarks/>
        public void ntfyElectronicVouchersAsync(infoAutSRIString infoAutSRIString, string debug, object userState) {
            if ((this.ntfyElectronicVouchersOperationCompleted == null)) {
                this.ntfyElectronicVouchersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnntfyElectronicVouchersOperationCompleted);
            }
            this.InvokeAsync("ntfyElectronicVouchers", new object[] {
                        infoAutSRIString,
                        debug}, this.ntfyElectronicVouchersOperationCompleted, userState);
        }
        
        private void OnntfyElectronicVouchersOperationCompleted(object arg) {
            if ((this.ntfyElectronicVouchersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ntfyElectronicVouchersCompleted(this, new ntfyElectronicVouchersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://latwisqa02.am.qua.lafargeone.net/laf.webServices.invoicec.infoAutSRIString" +
        ":infoAutSRIString")]
    public partial class infoAutSRIString {
        
        private infoAutSRIString2 infoAutSRIString1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("infoAutSRIString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public infoAutSRIString2 infoAutSRIString1 {
            get {
                return this.infoAutSRIString1Field;
            }
            set {
                this.infoAutSRIString1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://latwisqa02.am.qua.lafargeone.net/laf.webServices.invoicec.infoAutSRIString" +
        ":infoAutSRIString")]
    public partial class infoAutSRIString2 {
        
        private string p_codDocField;
        
        private string p_numDocField;
        
        private string p_AccesskeyField;
        
        private string p_AutorizacionField;
        
        private string p_AuthdateField;
        
        private string p_AuthtimeField;
        
        private string p_ContingencyField;
        
        private string p_ContdateField;
        
        private string p_ConttimeField;
        
        private string p_statusField;
        
        private string p_MessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string p_codDoc {
            get {
                return this.p_codDocField;
            }
            set {
                this.p_codDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string p_numDoc {
            get {
                return this.p_numDocField;
            }
            set {
                this.p_numDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string p_Accesskey {
            get {
                return this.p_AccesskeyField;
            }
            set {
                this.p_AccesskeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string p_Autorizacion {
            get {
                return this.p_AutorizacionField;
            }
            set {
                this.p_AutorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string p_Authdate {
            get {
                return this.p_AuthdateField;
            }
            set {
                this.p_AuthdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string p_Authtime {
            get {
                return this.p_AuthtimeField;
            }
            set {
                this.p_AuthtimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string p_Contingency {
            get {
                return this.p_ContingencyField;
            }
            set {
                this.p_ContingencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string p_Contdate {
            get {
                return this.p_ContdateField;
            }
            set {
                this.p_ContdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string p_Conttime {
            get {
                return this.p_ConttimeField;
            }
            set {
                this.p_ConttimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string p_status {
            get {
                return this.p_statusField;
            }
            set {
                this.p_statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string p_Message {
            get {
                return this.p_MessageField;
            }
            set {
                this.p_MessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ntfyElectronicVouchersCompletedEventHandler(object sender, ntfyElectronicVouchersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ntfyElectronicVouchersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ntfyElectronicVouchersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string o_message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591