//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CIMA02\\SQLEXPRESS;Initial Catalog=dataEcuador;Persist Security Info=T" +
            "rue;User ID=sa;Password=data_cima")]
        public string dataexpressConnectionString1 {
            get {
                return ((string)(this["dataexpressConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantes")]
        public string Control_receWeb_RecepcionComprobantesService {
            get {
                return ((string)(this["Control_receWeb_RecepcionComprobantesService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=dataEcuadorTorremar;User ID=sa;Password=12345" +
            "6")]
        public string dataexpressConnectionString {
            get {
                return ((string)(this["dataexpressConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=dataEcuadorTorremar;Persist Security Info=Tru" +
            "e;User ID=sa;Password=123456")]
        public string dataEcuadorTorremarConnectionString {
            get {
                return ((string)(this["dataEcuadorTorremarConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://latwisqa02.am.qua.lafargeone.net:8880/ws/laf.webServices.invoicec.infoAutS" +
            "RIString.infoAutSRIString/laf_webServices_invoicec_infoAutSRIString_infoAutSRISt" +
            "ring_Port")]
        public string Control_LFWSrpt_laf_webServices_invoicec_infoAutSRIString_infoAutSRIString {
            get {
                return ((string)(this["Control_LFWSrpt_laf_webServices_invoicec_infoAutSRIString_infoAutSRIString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sapdev.unacem.com.pe:8001/sap/bc/srt/rfc/sap/zecsrifm01/400/zecsrifm01/zec" +
            "srifm01")]
        public string Control_WebReference_ZECSRIFM01 {
            get {
                return ((string)(this["Control_WebReference_ZECSRIFM01"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sapdev.unacem.com.pe:5001/sap/bc/srt/rfc/sap/zecsrifm01")]
        public string Control_TestUnacemSap_ZECSRIFM01 {
            get {
                return ((string)(this["Control_TestUnacemSap_ZECSRIFM01"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes")]
        public string Control_autoweb_AutorizacionComprobantesService {
            get {
                return ((string)(this["Control_autoweb_AutorizacionComprobantesService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://aplicaciones.unacem.com.ec:8090/WebServiceUNACEM.asmx")]
        public string Control_mina_WebServiceUNACEM {
            get {
                return ((string)(this["Control_mina_WebServiceUNACEM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ordev.unacem.com.pe/wsUNACEMECSRI/svcUNACEMECSRI.svc")]
        public string Control_WebReference_SvcUNACEMECSRI {
            get {
                return ((string)(this["Control_WebReference_SvcUNACEMECSRI"]));
            }
        }
    }
}
