# Nombre del workflow que aparecerá en la pestaña "Actions"
name: 'Dependency Review'

# Define cuándo se ejecutará este workflow
on: [pull_request]

# Define los trabajos (jobs) que se ejecutarán
jobs:
  dependency-review:
    # El tipo de máquina virtual donde se ejecutará el trabajo
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Descarga una copia de tu código en la máquina virtual
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      # Paso 2: Ejecuta la acción de revisión de dependencias
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
